wget http://www.estadisticas.pr/coli/img/grnd_beef.png
wget http://www.estadisticas.pr/coli/img/tbone_steak.png
wget http://www.estadisticas.pr/coli/img/sausage.png
wget http://www.estadisticas.pr/coli/img/fry_chick.png
wget http://www.estadisticas.pr/coli/img/tuna.png
wget http://www.estadisticas.pr/coli/img/hgal_milk.png
wget http://www.estadisticas.pr/coli/img/dozen_eggs.png
wget http://www.estadisticas.pr/coli/img/margarine.png
wget http://www.estadisticas.pr/coli/img/parmesan.png
wget http://www.estadisticas.pr/coli/img/potatoes.png
wget http://www.estadisticas.pr/coli/img/bananas.png
wget http://www.estadisticas.pr/coli/img/lettuce.png
wget http://www.estadisticas.pr/coli/img/bread.png
wget http://www.estadisticas.pr/coli/img/orange_juic.png
wget http://www.estadisticas.pr/coli/img/coffee.png
wget http://www.estadisticas.pr/coli/img/sugar.png
wget http://www.estadisticas.pr/coli/img/cereal.png
wget http://www.estadisticas.pr/coli/img/sweet_peas.png
wget http://www.estadisticas.pr/coli/img/peaches.png
wget http://www.estadisticas.pr/coli/img/klnx.png
wget http://www.estadisticas.pr/coli/img/cascad.png
wget http://www.estadisticas.pr/coli/img/canola_oil.png
wget http://www.estadisticas.pr/coli/img/frozn_meal.png
wget http://www.estadisticas.pr/coli/img/frozn_corn.png
wget http://www.estadisticas.pr/coli/img/potato_chips.png
wget http://www.estadisticas.pr/coli/img/coke.png
wget http://www.estadisticas.pr/coli/img/apt_rent.png
wget http://www.estadisticas.pr/coli/img/home_price.png
wget http://www.estadisticas.pr/coli/img/doctor.png
wget http://www.estadisticas.pr/coli/img/total_energy.png
wget http://www.estadisticas.pr/coli/img/phone.png
wget http://www.estadisticas.pr/coli/img/tire_bal.png
wget http://www.estadisticas.pr/coli/img/gasoline.png
wget http://www.estadisticas.pr/coli/img/optometrist.png
wget http://www.estadisticas.pr/coli/img/dentist.png
wget http://www.estadisticas.pr/coli/img/ibuprofen.png
wget http://www.estadisticas.pr/coli/img/lipitor.png
wget http://www.estadisticas.pr/coli/img/hmbgr_sand.png
wget http://www.estadisticas.pr/coli/img/pizza.png
wget http://www.estadisticas.pr/coli/img/pc2_chick.png
wget http://www.estadisticas.pr/coli/img/haircut.png
wget http://www.estadisticas.pr/coli/img/beaut_salon.png
wget http://www.estadisticas.pr/coli/img/toothpaste.png
wget http://www.estadisticas.pr/coli/img/shampoo.png
wget http://www.estadisticas.pr/coli/img/dry_clean.png
wget http://www.estadisticas.pr/coli/img/mens_shirt.png
wget http://www.estadisticas.pr/coli/img/boys_jeans.png
wget http://www.estadisticas.pr/coli/img/womens_slacks.png
wget http://www.estadisticas.pr/coli/img/washr_repr.png
wget http://www.estadisticas.pr/coli/img/newspaper.png
wget http://www.estadisticas.pr/coli/img/movie.png
wget http://www.estadisticas.pr/coli/img/bowling.png
wget http://www.estadisticas.pr/coli/img/tenns_balls.png
wget http://www.estadisticas.pr/coli/img/vet_services.png
wget http://www.estadisticas.pr/coli/img/beer.png
wget http://www.estadisticas.pr/coli/img/wine.png